'use client'

import { useState, useEffect } from 'react'
import { languageStore } from '@/lib/languageStore'

type Language = 'en' | 'es'

export const useLanguageStore = () => {
  const [language, setLanguage] = useState<Language>('en')
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true)
    setLanguage(languageStore.getLanguage())
    const unsubscribe = languageStore.subscribe(setLanguage)
    return unsubscribe
  }, [])

  const toggleLanguage = () => {
    languageStore.toggleLanguage()
  }

  const translations = {
    en: {
      'nav.about': 'About',
      'nav.services': 'Services',
      'nav.properties': 'Properties',
      'nav.contact': 'Contact',
      'hero.title': 'Your North County Home Starts Here',
      'hero.subtitle': 'Guiding veterans families and investors to their next chapter',
      'hero.schedule_call': 'Schedule a Call',
      'hero.investment_options': 'See Investment Options',
      'services.badge': 'Specialized Services',
      'services.title': 'Who I Serve',
      'services.subtitle': 'I focus on three key client types, bringing specialized expertise to each relationship.',
      'services.veterans.title': 'Veterans',
      'services.veterans.description': 'Maximizing VA loan benefits and housing allowances',
      'services.veterans.feature1': 'VA Loan Expertise',
      'services.veterans.feature2': 'Military Housing Knowledge',
      'services.veterans.feature3': 'Camp Pendleton, Miramar & Coronado Focus',
      'services.veterans.button': 'Get Veteran Guide',
      'services.investors.title': 'Investors',
      'services.investors.description': 'House hacking, ADUs, and portfolio building',
      'services.investors.feature1': 'ADU Development',
      'services.investors.feature2': 'Cap Rate Analysis',
      'services.investors.feature3': 'Property Management',
      'services.investors.button': 'Investment Guide',
      'services.families.title': 'Growing Families',
      'services.families.description': 'First-time buyers and move-up opportunities',
      'services.families.feature1': 'First-Time Buyer Support',
      'services.families.feature2': 'Move-Up Strategies',
      'services.families.feature3': 'Community Knowledge',
      'services.families.button': 'Start Your Journey',
      'about.badge': 'About Ruben',
      'about.title': 'My Journey: Healthcare to Real Estate',
      'about.subtitle': 'A story of discipline, empathy, and commitment to helping families build their future',
      'about.step1.title': 'Doctor of Physical Therapy',
      'about.step1.description': 'Built a foundation in healthcare, learning the value of discipline, empathy, and service. Developed skills in patient care, problem-solving, and building trust with families during challenging times.',
      'about.step2.title': 'Building for Family & Community',
      'about.step2.description': 'Driven by the desire to help families achieve financial independence and create lasting legacies. Committed to serving the community that raised him, with a special focus on veterans, first-time buyers, and long-term investors.',
      'about.step3.title': 'Real Estate Transition',
      'about.step3.description': 'Leveraged healthcare expertise to become a licensed real estate broker and property manager. Applied the same principles of patient care to client relationships: listening, understanding needs, and providing expert guidance through complex processes.',
      'about.step4.title': 'Rising Star Recognition',
      'about.step4.description': 'Recognized as a 2024 "Rising Star" at Team Fearless, with expertise in VA loans, house hacking, and investment properties. NARPM certified and deeply connected to the North County community, serving veterans, families, and investors with integrity.',
      'about.button': 'Learn More About My Story',
      'contact.badge': 'Get In Touch',
      'contact.title': 'Ready to Start Your Journey?',
      'contact.subtitle': 'Let\'s discuss your real estate goals and create a strategy that works for you.',
      'contact.phone': 'Phone',
      'contact.email': 'Email',
      'contact.areas': 'Service Areas',
      'contact.areas.description': 'North County San Diego',
      'contact.schedule_button': 'Schedule a Call',
      'contact.form.title': 'Send a Message',
      'contact.form.first_name': 'First Name',
      'contact.form.first_name_placeholder': 'Enter your first name',
      'contact.form.last_name': 'Last Name',
      'contact.form.last_name_placeholder': 'Enter your last name',
      'contact.form.email': 'Email',
      'contact.form.email_placeholder': 'Enter your email',
      'contact.form.phone': 'Phone',
      'contact.form.phone_placeholder': 'Enter your phone number',
      'contact.form.client_type': 'I am a...',
      'contact.form.option1': 'Veteran',
      'contact.form.option2': 'Investor',
      'contact.form.option3': 'First-Time Buyer',
      'contact.form.option4': 'Property Management',
      'contact.form.option5': 'General Consultation',
      'contact.form.message': 'Message',
      'contact.form.message_placeholder': 'Tell me about your real estate goals...',
      'contact.form.submit': 'Send Message',
      'portfolio.badge': 'Portfolio',
      'portfolio.title': 'Project Gallery',
      'portfolio.subtitle': 'Showcasing successful real estate projects across North County San Diego',
      'portfolio.button': 'View Full Portfolio',
      'testimonials.badge': 'Testimonials',
      'testimonials.title': 'What Clients Say',
      'testimonials.subtitle': 'Real feedback from satisfied clients who trusted Ruben with their real estate needs',
      'testimonials.button': 'Read More Reviews',
      'testimonials.1': 'I am a real estate photographer and I work with a lot of realtors in San Diego. I know a great agent when I arrive to do the photos and the clients have the home 100% picture ready. Ruben does an excellent job setting the expectations for the seller\'s so his listings always stand out and they are setup for success from the start. Ruben is great guy, super knowledgeable, I would highly recommend him for real estate transactions or property management!',
      'testimonials.2': 'Ruben was incredibly helpful for us when we were looking for a tenant for our home. He is knowledgeable, responsive, kind, and understanding. He was able to learn with us and took all our feedback seriously. Couldn\'t recommend him enough. We will definitely be working with Ruben in the future for any placement or property manager needs.',
      'testimonials.3': 'Ruben is awesome! If there were a way to give him 6 stars I would. He is super responsive, and really stays on top of things well. It was very comforting to know we had someone who we could really trust throughout the process. He made everything very smooth and seamless, answered all of our questions and had excellent insight. If you\'re looking for a real estate agent, Ruben will exceed your expectations.',
      'testimonials.4': 'Ruben is exceptional at his craft and does an incredible job at guiding his clients every step of the way in a real estate transaction. He has deep knowledge of the market, great attention to detail, and always puts his clients interest first. You can expect great results when working with Ruben.',
      'testimonials.5': 'I have had the pleasure of working alongside Ruben on multiple transactions. His passion to serve and educate his clients along the way is truly remarkable. Ruben is hard working, diligent with the details, and gets the job done! Highly recommend him for not only real estate but also property management as well!',
      'testimonials.6': 'Ruben is very knowledgeable in the home buying and selling process. He educated his clients. He explains everything clearly. Always answers his phone. He makes the home buying/selling process smooth. He is patient and an has a lot of insight and expertise in the RE industry. Ruben listens to his clients needs.',
      'testimonials.7': 'Working with Ruben has been an absolute pleasure from start to finish. Not only is he an incredibly skilled real estate agent, but he goes above and beyond by offering invaluable mentorship along the way. As a first-time homebuyer, I was nervous about the entire process, but Ruben\'s guidance and expertise put me at ease right away. What sets Ruben apart is his genuine commitment to his clients\' success. He took the time to understand my needs and patiently answered all my questions, ensuring I felt confident at every step.',
      'testimonials.8': 'If you are looking for the best home buying experience, you have to work with Ruben. Ruben has every quality to not only make your homeownership dreams come true but also make the journey an enjoyable experience. He takes on every hurdle that may come along with professionalism and a great attitude. I am proud to say he is my realtor partner.',
      'testimonials.9': 'Ruben and his team went above and beyond expectations for us. He represented our interests very well as a buyer agent. Not only from a standpoint of typical broker work, but also his contact list of professional services. He has a stellar network of people that impressed us throughout the process. Thanks Ruben!',
      'testimonials.10': 'We were referred to Ruben by a friend who raved of his knowledge. We enjoyed his enthusiasm and his expertise in his field. He enlightened us to some things we would not have thought of, was very informative and eager to answer any and all questions, and was easy to work with. We want to thank him for his time, energy and effort in assisting us and always being available for our 100 questions. Ruben is definitely are go to guy going forward!',
      'service_areas.title': 'Local Expertise Where It Matters Most',
      'service_areas.subtitle': 'Knowledge of schools, commutes and neighborhood markets.',
      'service_areas.map_instruction': 'Click on the locations to explore each area',
      'service_areas.button': 'Explore My Service Areas',
      'features.button': 'View My Certifications',
      'service_areas.san_marcos.description': 'San Marcos is the hometown hub of North County. Known for its strong schools, family-friendly neighborhoods, and expanding business scene, it\'s a prime location for both first-time buyers and seasoned investors.',
      'service_areas.escondido.description': 'Escondido is a vibrant community in North County San Diego, offering excellent opportunities for both residents and investors. With its strategic location and growing amenities, it represents one of the most promising areas in the region.',
      'service_areas.vista.description': 'Vista blends affordability with opportunity, making it attractive for house hackers and families alike. With its mix of suburban comfort and new development, Vista continues to draw those looking for long-term growth.',
      'service_areas.carlsbad.description': 'Carlsbad is coastal living at its best. Families love its beaches and top-ranked schools, while investors see strong rental demand and appreciation potential. It\'s the perfect balance of lifestyle and return.',
      'service_areas.oceanside.description': 'Oceanside combines a relaxed beach vibe with a revitalized downtown and military presence. From VA loan opportunities to waterfront investments, it offers something unique for veterans, families, and investors.',
      'footer.title': 'Ready to Start Your Real Estate Journey?',
      'footer.subtitle': 'Let\'s discuss your goals and create a strategy that works for you.',
      'footer.services_title': 'Services',
      'footer.service1': 'Veterans',
      'footer.service2': 'Investors',
      'footer.service3': 'First-Time Buyers',
      'footer.service4': 'Property Management',
      'footer.areas_title': 'Areas',
      'footer.contact_title': 'Contact',
      'footer.copyright': '© 2025 Ruben Real Estate. All rights reserved. | Realty of America (ROA)',
    },
    es: {
      'nav.about': 'Acerca de',
      'nav.services': 'Servicios',
      'nav.properties': 'Propiedades',
      'nav.contact': 'Contacto',
      'hero.title': 'Tu Hogar en North County Comienza Aquí',
      'hero.subtitle': 'Guiando a veteranos, familias e inversionistas hacia su próximo capítulo',
      'hero.schedule_call': 'Programar una Llamada',
      'hero.investment_options': 'Ver Opciones de Inversión',
      'services.badge': 'Servicios Especializados',
      'services.title': 'A Quién Sirvo',
      'services.subtitle': 'Me enfoco en tres tipos de clientes clave, aportando experiencia especializada a cada relación.',
      'services.veterans.title': 'Veteranos',
      'services.veterans.description': 'Maximizando beneficios de préstamos VA y subsidios de vivienda',
      'services.veterans.feature1': 'Experiencia en Préstamos VA',
      'services.veterans.feature2': 'Conocimiento de Vivienda Militar',
      'services.veterans.feature3': 'Enfoque en Camp Pendleton, Miramar y Coronado',
      'services.veterans.button': 'Obtener Guía para Veteranos',
      'services.investors.title': 'Inversionistas',
      'services.investors.description': 'House hacking, ADUs y construcción de portafolio',
      'services.investors.feature1': 'Desarrollo de ADU',
      'services.investors.feature2': 'Análisis de Tasa de Capitalización',
      'services.investors.feature3': 'Administración de Propiedades',
      'services.investors.button': 'Guía de Inversión',
      'services.families.title': 'Familias en Crecimiento',
      'services.families.description': 'Compradores primerizos y oportunidades de mejora',
      'services.families.feature1': 'Apoyo a Compradores Primerizos',
      'services.families.feature2': 'Estrategias de Mejora',
      'services.families.feature3': 'Conocimiento de la Comunidad',
      'services.families.button': 'Comienza tu Viaje',
      'about.badge': 'Acerca de Ruben',
      'about.title': 'Mi Viaje: De la Salud al Bienes Raíces',
      'about.subtitle': 'Una historia de disciplina, empatía y compromiso para ayudar a las familias a construir su futuro',
      'about.step1.title': 'Doctor en Terapia Física',
      'about.step1.description': 'Construí una base en salud, aprendiendo el valor de la disciplina, empatía y servicio. Desarrollé habilidades en cuidado de pacientes, resolución de problemas y construcción de confianza con familias durante tiempos desafiantes.',
      'about.step2.title': 'Construyendo para la Familia y la Comunidad',
      'about.step2.description': 'Mi mayor motivación es apoyar a las familias a lograr independencia financiera y dejar un legado duradero. Estoy comprometido con servir a la comunidad que me vio crecer, con un enfoque especial en veteranos, compradores primerizos e inversionistas a largo plazo.',
      'about.step3.title': 'Transición al Bienes Raíces',
      'about.step3.description': 'Transformé mi experiencia en salud en una carrera como corredor de bienes raíces y administrador de propiedades. Apliqué los mismos principios del cuidado de pacientes a mis clientes: escuchar, entender sus necesidades y guiarlos con experiencia en procesos complejos.',
      'about.step4.title': 'Reconocimiento Rising Star',
      'about.step4.description': 'Fui reconocido en 2024 como "Rising Star" en Team Fearless, con especialización en préstamos VA, house hacking y propiedades de inversión. Como miembro certificado de NARPM y profundamente conectado con la comunidad de North County, sirvo a veteranos, familias e inversionistas con integridad y compromiso.',
      'about.button': 'Conoce Más Mi Historia',
      'contact.badge': 'Ponte en Contacto',
      'contact.title': '¿Listo para Comenzar tu Viaje?',
      'contact.subtitle': 'Hablemos de tus objetivos inmobiliarios y creemos una estrategia que funcione para ti.',
      'contact.phone': 'Teléfono',
      'contact.email': 'Correo Electrónico',
      'contact.areas': 'Áreas de Servicio',
      'contact.areas.description': 'North County San Diego',
      'contact.schedule_button': 'Programar una Llamada',
      'contact.form.title': 'Enviar un Mensaje',
      'contact.form.first_name': 'Nombre',
      'contact.form.first_name_placeholder': 'Ingresa tu nombre',
      'contact.form.last_name': 'Apellido',
      'contact.form.last_name_placeholder': 'Ingresa tu apellido',
      'contact.form.email': 'Correo Electrónico',
      'contact.form.email_placeholder': 'Ingresa tu correo',
      'contact.form.phone': 'Teléfono',
      'contact.form.phone_placeholder': 'Ingresa tu número de teléfono',
      'contact.form.client_type': 'Soy un...',
      'contact.form.option1': 'Veterano',
      'contact.form.option2': 'Inversionista',
      'contact.form.option3': 'Comprador Primerizo',
      'contact.form.option4': 'Administración de Propiedades',
      'contact.form.option5': 'Consulta General',
      'contact.form.message': 'Mensaje',
      'contact.form.message_placeholder': 'Cuéntame sobre tus objetivos inmobiliarios...',
      'contact.form.submit': 'Enviar Mensaje',
      'portfolio.badge': 'Portafolio',
      'portfolio.title': 'Galería de Proyectos',
      'portfolio.subtitle': 'Mostrando proyectos inmobiliarios exitosos en North County San Diego',
      'portfolio.button': 'Ver Portafolio Completo',
      'testimonials.badge': 'Testimonios',
      'testimonials.title': 'Lo Que Dicen los Clientes',
      'testimonials.subtitle': 'Comentarios reales de clientes satisfechos que confiaron en Ruben para sus necesidades inmobiliarias',
      'testimonials.button': 'Leer Más Reseñas',
      'testimonials.1': 'Soy un fotógrafo inmobiliario y trabajo con muchos agentes en San Diego. Sé cuándo un agente es excelente cuando llego a hacer las fotos y los clientes tienen la casa 100% lista para las fotos. Ruben hace un trabajo excelente estableciendo las expectativas para los vendedores, por lo que sus listados siempre se destacan y están configurados para el éxito desde el principio. Ruben es un gran tipo, súper conocedor, ¡lo recomiendo altamente para transacciones inmobiliarias o administración de propiedades!',
      'testimonials.2': 'Ruben fue increíblemente útil para nosotros cuando estábamos buscando un inquilino para nuestra casa. Es conocedor, receptivo, amable y comprensivo. Pudo aprender con nosotros y tomó todos nuestros comentarios en serio. No podría recomendarlo lo suficiente. Definitivamente trabajaremos con Ruben en el futuro para cualquier colocación o necesidades de administrador de propiedades.',
      'testimonials.3': '¡Ruben es increíble! Si hubiera una manera de darle 6 estrellas lo haría. Es súper receptivo y realmente se mantiene al tanto de las cosas. Fue muy reconfortante saber que teníamos a alguien en quien realmente podíamos confiar durante todo el proceso. Hizo que todo fuera muy suave y sin problemas, respondió todas nuestras preguntas y tuvo excelentes ideas. Si estás buscando un agente inmobiliario, Ruben superará tus expectativas.',
      'testimonials.4': 'Ruben es excepcional en su oficio y hace un trabajo increíble guiando a sus clientes en cada paso del camino en una transacción inmobiliaria. Tiene un profundo conocimiento del mercado, gran atención al detalle y siempre pone los intereses de sus clientes primero. Puedes esperar grandes resultados cuando trabajes con Ruben.',
      'testimonials.5': 'He tenido el placer de trabajar junto a Ruben en múltiples transacciones. Su pasión por servir y educar a sus clientes en el camino es verdaderamente notable. Ruben es trabajador, diligente con los detalles y ¡hace el trabajo! ¡Lo recomiendo altamente no solo para bienes raíces sino también para administración de propiedades!',
      'testimonials.6': 'Ruben es muy conocedor en el proceso de compra y venta de casas. Educa a sus clientes. Explica todo claramente. Siempre contesta su teléfono. Hace que el proceso de compra/venta de casa sea suave. Es paciente y tiene mucha perspicacia y experiencia en la industria inmobiliaria. Ruben escucha las necesidades de sus clientes.',
      'testimonials.7': 'Trabajar con Ruben ha sido un placer absoluto de principio a fin. No solo es un agente inmobiliario increíblemente hábil, sino que va más allá ofreciendo una mentoría invaluable en el camino. Como compradora de casa por primera vez, estaba nerviosa por todo el proceso, pero la guía y experiencia de Ruben me tranquilizaron de inmediato. Lo que distingue a Ruben es su compromiso genuino con el éxito de sus clientes. Se tomó el tiempo para entender mis necesidades y respondió pacientemente todas mis preguntas, asegurándose de que me sintiera confiada en cada paso.',
      'testimonials.8': 'Si estás buscando la mejor experiencia de compra de casa, tienes que trabajar con Ruben. Ruben tiene todas las cualidades para no solo hacer realidad tus sueños de propiedad de casa sino también hacer que el viaje sea una experiencia agradable. Asume cada obstáculo que pueda surgir con profesionalismo y una gran actitud. Estoy orgullosa de decir que es mi socio agente inmobiliario.',
      'testimonials.9': 'Ruben y su equipo fueron más allá de las expectativas para nosotros. Representó muy bien nuestros intereses como agente comprador. No solo desde el punto de vista del trabajo típico de corredor, sino también su lista de contactos de servicios profesionales. Tiene una red estelar de personas que nos impresionaron durante todo el proceso. ¡Gracias Ruben!',
      'testimonials.10': 'Nos refirieron a Ruben por un amigo que elogió su conocimiento. Disfrutamos su entusiasmo y su experiencia en su campo. Nos iluminó sobre algunas cosas en las que no habríamos pensado, fue muy informativo y ansioso por responder cualquier y todas las preguntas, y fue fácil trabajar con él. Queremos agradecerle por su tiempo, energía y esfuerzo en asistirnos y siempre estar disponible para nuestras 100 preguntas. ¡Ruben es definitivamente nuestro tipo de persona para el futuro!',
      'service_areas.title': 'Experiencia Local Donde Más Importa',
      'service_areas.subtitle': 'Conocimiento de escuelas, desplazamientos y mercados vecinales.',
      'service_areas.map_instruction': 'Haz clic en las ubicaciones para explorar cada área',
      'service_areas.button': 'Explora Mis Áreas de Servicio',
      'features.button': 'Ver Mis Certificaciones',
      'service_areas.san_marcos.description': 'San Marcos es el centro de North County. Conocido por sus excelentes escuelas, vecindarios familiares y escena empresarial en expansión, es una ubicación principal tanto para compradores primerizos como para inversionistas experimentados.',
      'service_areas.escondido.description': 'Escondido es una comunidad vibrante en North County San Diego, que ofrece excelentes oportunidades tanto para residentes como para inversionistas. Con su ubicación estratégica y crecientes comodidades, representa una de las áreas más prometedoras de la región.',
      'service_areas.vista.description': 'Vista combina asequibilidad con oportunidad, haciéndola atractiva tanto para house hackers como para familias. Con su mezcla de comodidad suburbana y nuevo desarrollo, Vista continúa atrayendo a aquellos que buscan crecimiento a largo plazo.',
      'service_areas.carlsbad.description': 'Carlsbad es la vida costera en su mejor expresión. Las familias aman sus playas y escuelas de alto rango, mientras que los inversionistas ven una fuerte demanda de alquiler y potencial de apreciación. Es el equilibrio perfecto entre estilo de vida y retorno.',
      'service_areas.oceanside.description': 'Oceanside combina un ambiente de playa relajado con un centro revitalizado y presencia militar. Desde oportunidades de préstamos VA hasta inversiones en el frente marítimo, ofrece algo único para veteranos, familias e inversionistas.',
      'footer.title': '¿Listo para Comenzar tu Viaje Inmobiliario?',
      'footer.subtitle': 'Hablemos de tus objetivos y creemos una estrategia que funcione para ti.',
      'footer.services_title': 'Servicios',
      'footer.service1': 'Veteranos',
      'footer.service2': 'Inversionistas',
      'footer.service3': 'Compradores Primerizos',
      'footer.service4': 'Administración de Propiedades',
      'footer.areas_title': 'Áreas',
      'footer.contact_title': 'Contacto',
      'footer.copyright': '© 2025 Ruben Real Estate. Todos los derechos reservados. | Realty of America (ROA)',
    }
  }

  const t = (key: string): string => {
    // During SSR or before client hydration, always return English
    if (!isClient) {
      return translations['en'][key as keyof typeof translations['en']] || key
    }
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return { language, toggleLanguage, t }
}