'use client'

import { useState, useEffect } from 'react'
import { languageStore } from '@/lib/languageStore'

type Language = 'en' | 'es'

export default function useLanguageStore() {
  const [language, setLanguage] = useState<Language>('en')
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true)
    setLanguage(languageStore.getLanguage())
    const unsubscribe = languageStore.subscribe(setLanguage)
    return unsubscribe
  }, [])

  const toggleLanguage = () => {
    languageStore.toggleLanguage()
  }

  const translations = {
    en: {
      'nav.about': 'About',
      'nav.services': 'Services',
      'nav.properties': 'Properties',
      'nav.contact': 'Contact',
      'hero.title': 'Your North County Home Starts Here',
      'hero.subtitle': 'Guiding veterans families and investors to their next chapter',
      'hero.schedule_call': 'Schedule a Call',
      'hero.investment_options': 'See Investment Options',
      'services.badge': 'Specialized Services',
      'services.title': 'Who I Serve',
      'services.subtitle': 'I focus on three key client types, bringing specialized expertise to each relationship.',
      'services.veterans.title': 'Veterans',
      'services.veterans.description': 'Maximizing VA loan benefits and housing allowances',
      'services.veterans.feature1': 'VA Loan Expertise',
      'services.veterans.feature2': 'Military Housing Knowledge',
      'services.veterans.feature3': 'Camp Pendleton, Miramar & Coronado Focus',
      'services.veterans.button': 'Get Veteran Guide',
      'services.investors.title': 'Investors',
      'services.investors.description': 'House hacking, ADUs, and portfolio building',
      'services.investors.feature1': 'ADU Development',
      'services.investors.feature2': 'Cap Rate Analysis',
      'services.investors.feature3': 'Property Management',
      'services.investors.button': 'Investment Guide',
      'services.families.title': 'Growing Families',
      'services.families.description': 'First-time buyers and move-up opportunities',
      'services.families.feature1': 'First-Time Buyer Support',
      'services.families.feature2': 'Move-Up Strategies',
      'services.families.feature3': 'Community Knowledge',
      'services.families.button': 'Start Your Journey',
      'about.badge': 'About Ruben',
      'about.title': 'My Journey: Healthcare to Real Estate',
      'about.subtitle': 'A story of discipline, empathy, and commitment to helping families build their future',
      'about.step1.title': 'Doctor of Physical Therapy',
      'about.step1.description': 'Built a foundation in healthcare, learning the value of discipline, empathy, and service. Developed skills in patient care, problem-solving, and building trust with families during challenging times.',
      'about.step2.title': 'Building for Family & Community',
      'about.step2.description': 'Driven by the desire to help families achieve financial independence and create lasting legacies. Committed to serving the community that raised him, with a special focus on veterans, first-time buyers, and long-term investors.',
      'about.step3.title': 'Real Estate Transition',
      'about.step3.description': 'Leveraged healthcare expertise to become a licensed real estate broker and property manager. Applied the same principles of patient care to client relationships: listening, understanding needs, and providing expert guidance through complex processes.',
      'about.step4.title': 'Rising Star Recognition',
      'about.step4.description': 'Recognized as a 2024 "Rising Star" at Team Fearless, with expertise in VA loans, house hacking, and investment properties. NARPM certified and deeply connected to the North County community, serving veterans, families, and investors with integrity.',
      'about.button': 'Learn More About My Story',
      'contact.badge': 'Get In Touch',
      'contact.title': 'Ready to Start Your Journey?',
      'contact.subtitle': 'Let\'s discuss your real estate goals and create a strategy that works for you.',
      'contact.phone': 'Phone',
      'contact.email': 'Email',
      'contact.areas': 'Service Areas',
      'contact.areas.description': 'North County San Diego',
      'contact.schedule_button': 'Schedule a Call',
      'contact.form.title': 'Send a Message',
      'contact.form.first_name': 'First Name',
      'contact.form.first_name_placeholder': 'Enter your first name',
      'contact.form.last_name': 'Last Name',
      'contact.form.last_name_placeholder': 'Enter your last name',
      'contact.form.email': 'Email',
      'contact.form.email_placeholder': 'Enter your email',
      'contact.form.phone': 'Phone',
      'contact.form.phone_placeholder': 'Enter your phone number',
      'contact.form.client_type': 'I am a...',
      'contact.form.option1': 'Veteran',
      'contact.form.option2': 'Investor',
      'contact.form.option3': 'First-Time Buyer',
      'contact.form.option4': 'Property Management',
      'contact.form.option5': 'General Consultation',
      'contact.form.message': 'Message',
      'contact.form.message_placeholder': 'Tell me about your real estate goals...',
      'contact.form.submit': 'Send Message',
      'portfolio.badge': 'Portfolio',
      'portfolio.title': 'Project Gallery',
      'portfolio.subtitle': 'Showcasing successful real estate projects across North County San Diego',
      'portfolio.button': 'View Full Portfolio',
      'testimonials.badge': 'Testimonials',
      'testimonials.title': 'What Clients Say',
      'testimonials.subtitle': 'Real feedback from satisfied clients who trusted Ruben with their real estate needs',
      'testimonials.button': 'Read More Reviews',
      'testimonials.1': 'I am a real estate photographer and I work with a lot of realtors in San Diego. I know a great agent when I arrive to do the photos and the clients have the home 100% picture ready. Ruben does an excellent job setting the expectations for the seller\'s so his listings always stand out and they are setup for success from the start. Ruben is great guy, super knowledgeable, I would highly recommend him for real estate transactions or property management!',
      'testimonials.2': 'Ruben was incredibly helpful for us when we were looking for a tenant for our home. He is knowledgeable, responsive, kind, and understanding. He was able to learn with us and took all our feedback seriously. Couldn\'t recommend him enough. We will definitely be working with Ruben in the future for any placement or property manager needs.',
      'testimonials.3': 'Ruben is awesome! If there were a way to give him 6 stars I would. He is super responsive, and really stays on top of things well. It was very comforting to know we had someone who we could really trust throughout the process. He made everything very smooth and seamless, answered all of our questions and had excellent insight. If you\'re looking for a real estate agent, Ruben will exceed your expectations.',
      'testimonials.4': 'Ruben is exceptional at his craft and does an incredible job at guiding his clients every step of the way in a real estate transaction. He has deep knowledge of the market, great attention to detail, and always puts his clients interest first. You can expect great results when working with Ruben.',
      'testimonials.5': 'I have had the pleasure of working alongside Ruben on multiple transactions. His passion to serve and educate his clients along the way is truly remarkable. Ruben is hard working, diligent with the details, and gets the job done! Highly recommend him for not only real estate but also property management as well!',
      'testimonials.6': 'Ruben is very knowledgeable in the home buying and selling process. He educated his clients. He explains everything clearly. Always answers his phone. He makes the home buying/selling process smooth. He is patient and an has a lot of insight and expertise in the RE industry. Ruben listens to his clients needs.',
      'testimonials.7': 'Working with Ruben has been an absolute pleasure from start to finish. Not only is he an incredibly skilled real estate agent, but he goes above and beyond by offering invaluable mentorship along the way. As a first-time homebuyer, I was nervous about the entire process, but Ruben\'s guidance and expertise put me at ease right away. What sets Ruben apart is his genuine commitment to his clients\' success. He took the time to understand my needs and patiently answered all my questions, ensuring I felt confident at every step.',
      'testimonials.8': 'If you are looking for the best home buying experience, you have to work with Ruben. Ruben has every quality to not only make your homeownership dreams come true but also make the journey an enjoyable experience. He takes on every hurdle that may come along with professionalism and a great attitude. I am proud to say he is my realtor partner.',
      'testimonials.9': 'Ruben and his team went above and beyond expectations for us. He represented our interests very well as a buyer agent. Not only from a standpoint of typical broker work, but also his contact list of professional services. He has a stellar network of people that impressed us throughout the process. Thanks Ruben!',
      'testimonials.10': 'We were referred to Ruben by a friend who raved of his knowledge. We enjoyed his enthusiasm and his expertise in his field. He enlightened us to some things we would not have thought of, was very informative and eager to answer any and all questions, and was easy to work with. We want to thank him for his time, energy and effort in assisting us and always being available for our 100 questions. Ruben is definitely are go to guy going forward!',
      'service_areas.title': 'Local Expertise Where It Matters Most',
      'service_areas.subtitle': 'Knowledge of schools, commutes and neighborhood markets.',
      'service_areas.map_instruction': 'Click on the locations to explore each area',
      'service_areas.button': 'Explore My Service Areas',
      'features.button': 'View My Certifications',
      'service_areas.san_marcos.description': 'San Marcos is the hometown hub of North County. Known for its strong schools, family-friendly neighborhoods, and expanding business scene, it\'s a prime location for both first-time buyers and seasoned investors.',
      'service_areas.escondido.description': 'Escondido is a vibrant community in North County San Diego, offering excellent opportunities for both residents and investors. With its strategic location and growing amenities, it represents one of the most promising areas in the region.',
      'service_areas.vista.description': 'Vista blends affordability with opportunity, making it attractive for house hackers and families alike. With its mix of suburban comfort and new development, Vista continues to draw those looking for long-term growth.',
      'service_areas.carlsbad.description': 'Carlsbad is coastal living at its best. Families love its beaches and top-ranked schools, while investors see strong rental demand and appreciation potential. It\'s the perfect balance of lifestyle and return.',
      'service_areas.oceanside.description': 'Oceanside combines a relaxed beach vibe with a revitalized downtown and military presence. From VA loan opportunities to waterfront investments, it offers something unique for veterans, families, and investors.',
      'footer.title': 'Ready to Start Your Real Estate Journey?',
      'footer.subtitle': 'Let\'s discuss your goals and create a strategy that works for you.',
      'footer.services_title': 'Services',
      'footer.service1': 'Veterans',
      'footer.service2': 'Investors',
      'footer.service3': 'First-Time Buyers',
      'footer.service4': 'Property Management',
      'footer.areas_title': 'Areas',
      'footer.contact_title': 'Contact',
      'footer.slogan': 'Your North County Home Starts Here',
      'footer.copyright': '© 2025 Ruben Real Estate. All rights reserved. | Realty of America (ROA)',
      // Legal & compliance
      'legal.and': 'and',
      'contact.form.opt_in': "I agree to be contacted by Ruben Real Estate via call, email, and text for real estate services. To opt out, you can reply 'stop' at any time or reply 'help' for assistance. You can also click the unsubscribe link in the emails. Message and data rates may apply. Message frequency may vary.",
      'legal.no_sale_share': 'Data will not be sold or shared with third parties for promotional or marketing purposes.',
      'legal.link.privacy': 'Privacy Policy',
      'legal.link.terms': 'Terms of Use',
      'legal.privacy.title': 'Privacy Policy',
      'legal.privacy.intro': 'Welcome, and thank you for choosing Ruben Real Estate. This Privacy Policy explains how we collect, use, and safeguard your information when you use our website and services.',
      'legal.privacy.consent.title': 'Consent',
      'legal.privacy.consent': 'By using our website, you consent to this Privacy Policy and agree to its terms.',
      'legal.privacy.information.title': 'Information We Collect',
      'legal.privacy.collect': 'We may collect personal information such as your name, email address, phone number, and any other details you choose to provide when you contact us or submit forms on our site.',
      'legal.privacy.use.title': 'How We Use Your Information',
      'legal.privacy.use.1': 'Provide, operate, and maintain our website and services',
      'legal.privacy.use.2': 'Communicate with you about real estate services, including by call, email, and text',
      'legal.privacy.use.3': 'Respond to your inquiries and provide customer support',
      'legal.privacy.use.4': 'Improve and personalize your experience',
      'legal.privacy.use.5': 'Detect, prevent, and address fraud or security issues',
      'legal.privacy.logfiles.title': 'Log Files',
      'legal.privacy.logfiles': 'Like many websites, we use log files for analytics and site administration. This may include IP addresses, browser type, ISP, date/time stamp, referring/exit pages, and click counts. This information is not linked to personally identifiable information.',
      'legal.privacy.cookies.title': 'Cookies',
      'legal.privacy.cookies': 'We use cookies to remember preferences and improve your experience. You can control cookies through your browser settings.',
      'legal.privacy.rights.title': 'Your Rights',
      'legal.privacy.rights': 'Depending on your location, you may have rights to access, correct, delete, or restrict processing of your personal data, and to object to processing or request data portability. To exercise these rights, please contact us.',
      'legal.privacy.children.title': "Children's Information",
      'legal.privacy.children': "We do not knowingly collect personal information from children under 13. If you believe a child has provided us with personal data, contact us so we can remove it.",
      'legal.privacy.changes.title': 'Changes to This Policy',
      'legal.privacy.changes': 'We may update this Privacy Policy from time to time. Changes will be posted on this page and are effective when posted.',
      'legal.privacy.contact.title': 'Contact',
      'legal.privacy.contact_label': 'For questions about this Privacy Policy or to exercise your rights, contact us at',
      'legal.terms.title': 'Website Terms and Conditions of Use',
      'legal.terms.terms': 'By accessing this website, you agree to be bound by these Website Terms and Conditions of Use and agree that you are responsible for compliance with any applicable local laws. If you disagree with any of these terms, you are prohibited from accessing this site. The materials on this website are protected by copyright and trademark law.',
      'legal.terms.use_license.title': 'Use License',
      'legal.terms.use_license.body': "Permission is granted to temporarily download one copy of the materials on Ruben Real Estate's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not: modify or copy the materials; use the materials for any commercial purpose or for any public display; attempt to reverse engineer any software contained on this website; remove any copyright or other proprietary notations from the materials; or transfer the materials to another person or 'mirror' the materials on any other server. Ruben Real Estate may terminate this license upon violations of any of these restrictions. Upon termination, your viewing right will also be terminated and you must destroy any downloaded materials in your possession whether in printed or electronic format.",
      'legal.terms.disclaimer.title': 'Disclaimer',
      'legal.terms.disclaimer.body': 'All materials on this website are provided “as is.” Ruben Real Estate makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties. Further, Ruben Real Estate does not make any representations concerning the accuracy or reliability of the use of the materials on its website or otherwise relating to such materials or any sites linked to this website.',
      'legal.terms.limitations.title': 'Limitations',
      'legal.terms.limitations.body': 'In no event shall Ruben Real Estate or its suppliers be liable for any damages arising out of the use or inability to use the materials on the website, even if Ruben Real Estate or an authorized representative has been notified of the possibility of such damage. Some jurisdictions do not allow limitations on implied warranties or limitations of liability for incidental damages; these limitations may not apply to you.',
      'legal.terms.revisions.title': 'Revisions and Errata',
      'legal.terms.revisions.body': 'The materials appearing on this website may include technical, typographical, or photographic errors. Ruben Real Estate does not warrant that any of the materials on its website are accurate, complete, or current. Ruben Real Estate may make changes to the materials contained on its website at any time without notice. Ruben Real Estate does not make any commitment to update the materials.',
      'legal.terms.links.title': 'Links',
      'legal.terms.links.body': 'Ruben Real Estate has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Ruben Real Estate. Use of any such linked website is at the user’s own risk.',
      'legal.terms.modifications.title': 'Site Terms of Use Modifications',
      'legal.terms.modifications.body': 'Ruben Real Estate may revise these Terms of Use for its website at any time without prior notice. By using this website, you agree to be bound by the then-current version of these Terms and Conditions of Use.',
      'legal.terms.privacy_prompt': 'Your Privacy: Please read our',
      'legal.terms.governing_law.title': 'Governing Law',
      'legal.terms.governing_law.body': 'Any claim related to this website shall be governed by the laws of the United States without regard to its conflict of law provisions.',
      'legal.terms.contact.title': 'Contact Us',
      'legal.terms.contact.body': 'For questions about these Terms, contact us at ruben.o.banuelos@gmail.com or (541) 602-1026.',
    },
    es: {
      'nav.about': 'Acerca de',
      'nav.services': 'Servicios',
      'nav.properties': 'Propiedades',
      'nav.contact': 'Contacto',
      'hero.title': 'Tu Hogar en North County Comienza Aquí',
      'hero.subtitle': 'Guiando a veteranos, familias e inversionistas hacia su próximo capítulo',
      'hero.schedule_call': 'Programar una Llamada',
      'hero.investment_options': 'Ver Opciones de Inversión',
      'services.badge': 'Servicios Especializados',
      'services.title': 'A Quién Sirvo',
      'services.subtitle': 'Me enfoco en tres tipos de clientes clave, aportando experiencia especializada a cada relación.',
      'services.veterans.title': 'Veteranos',
      'services.veterans.description': 'Maximizando beneficios de préstamos VA y subsidios de vivienda',
      'services.veterans.feature1': 'Experiencia en Préstamos VA',
      'services.veterans.feature2': 'Conocimiento de Vivienda Militar',
      'services.veterans.feature3': 'Enfoque en Camp Pendleton, Miramar y Coronado',
      'services.veterans.button': 'Obtener Guía para Veteranos',
      'services.investors.title': 'Inversionistas',
      'services.investors.description': 'House hacking, ADUs y construcción de portafolio',
      'services.investors.feature1': 'Desarrollo de ADU',
      'services.investors.feature2': 'Análisis de Tasa de Capitalización',
      'services.investors.feature3': 'Administración de Propiedades',
      'services.investors.button': 'Guía de Inversión',
      'services.families.title': 'Familias en Crecimiento',
      'services.families.description': 'Compradores primerizos y oportunidades de mejora',
      'services.families.feature1': 'Apoyo a Compradores Primerizos',
      'services.families.feature2': 'Estrategias de Mejora',
      'services.families.feature3': 'Conocimiento de la Comunidad',
      'services.families.button': 'Comienza tu Viaje',
      'about.badge': 'Acerca de Ruben',
      'about.title': 'Mi Viaje: De la Salud al Bienes Raíces',
      'about.subtitle': 'Una historia de disciplina, empatía y compromiso para ayudar a las familias a construir su futuro',
      'about.step1.title': 'Doctor en Terapia Física',
      'about.step1.description': 'Construí una base en salud, aprendiendo el valor de la disciplina, empatía y servicio. Desarrollé habilidades en cuidado de pacientes, resolución de problemas y construcción de confianza con familias durante tiempos desafiantes.',
      'about.step2.title': 'Construyendo para la Familia y la Comunidad',
      'about.step2.description': 'Mi mayor motivación es apoyar a las familias a lograr independencia financiera y dejar un legado duradero. Estoy comprometido con servir a la comunidad que me vio crecer, con un enfoque especial en veteranos, compradores primerizos e inversionistas a largo plazo.',
      'about.step3.title': 'Transición al Bienes Raíces',
      'about.step3.description': 'Transformé mi experiencia en salud en una carrera como corredor de bienes raíces y administrador de propiedades. Apliqué los mismos principios del cuidado de pacientes a mis clientes: escuchar, entender sus necesidades y guiarlos con experiencia en procesos complejos.',
      'about.step4.title': 'Reconocimiento Rising Star',
      'about.step4.description': 'Fui reconocido en 2024 como "Rising Star" en Team Fearless, con especialización en préstamos VA, house hacking y propiedades de inversión. Como miembro certificado de NARPM y profundamente conectado con la comunidad de North County, sirvo a veteranos, familias e inversionistas con integridad y compromiso.',
      'about.button': 'Conoce Más Mi Historia',
      'contact.badge': 'Ponte en Contacto',
      'contact.title': '¿Listo para Comenzar tu Viaje?',
      'contact.subtitle': 'Hablemos de tus objetivos inmobiliarios y creemos una estrategia que funcione para ti.',
      'contact.phone': 'Teléfono',
      'contact.email': 'Correo Electrónico',
      'contact.areas': 'Áreas de Servicio',
      'contact.areas.description': 'North County San Diego',
      'contact.schedule_button': 'Programar una Llamada',
      'contact.form.title': 'Enviar un Mensaje',
      'contact.form.first_name': 'Nombre',
      'contact.form.first_name_placeholder': 'Ingresa tu nombre',
      'contact.form.last_name': 'Apellido',
      'contact.form.last_name_placeholder': 'Ingresa tu apellido',
      'contact.form.email': 'Correo Electrónico',
      'contact.form.email_placeholder': 'Ingresa tu correo',
      'contact.form.phone': 'Teléfono',
      'contact.form.phone_placeholder': 'Ingresa tu número de teléfono',
      'contact.form.client_type': 'Soy un...',
      'contact.form.option1': 'Veterano',
      'contact.form.option2': 'Inversionista',
      'contact.form.option3': 'Comprador Primerizo',
      'contact.form.option4': 'Administración de Propiedades',
      'contact.form.option5': 'Consulta General',
      'contact.form.message': 'Mensaje',
      'contact.form.message_placeholder': 'Cuéntame sobre tus objetivos inmobiliarios...',
      'contact.form.submit': 'Enviar Mensaje',
      'portfolio.badge': 'Portafolio',
      'portfolio.title': 'Galería de Proyectos',
      'portfolio.subtitle': 'Mostrando proyectos inmobiliarios exitosos en North County San Diego',
      'portfolio.button': 'Ver Portafolio Completo',
      'testimonials.badge': 'Testimonios',
      'testimonials.title': 'Lo Que Dicen los Clientes',
      'testimonials.subtitle': 'Comentarios reales de clientes satisfechos que confiaron en Ruben para sus necesidades inmobiliarias',
      'testimonials.button': 'Leer Más Reseñas',
      'testimonials.1': 'Soy un fotógrafo inmobiliario y trabajo con muchos agentes en San Diego. Sé cuándo un agente es excelente cuando llego a hacer las fotos y los clientes tienen la casa 100% lista para las fotos. Ruben hace un trabajo excelente estableciendo las expectativas para los vendedores, por lo que sus listados siempre se destacan y están configurados para el éxito desde el principio. Ruben es un gran tipo, súper conocedor, ¡lo recomiendo altamente para transacciones inmobiliarias o administración de propiedades!',
      'testimonials.2': 'Ruben fue increíblemente útil para nosotros cuando estábamos buscando un inquilino para nuestra casa. Es conocedor, receptivo, amable y comprensivo. Pudo aprender con nosotros y tomó todos nuestros comentarios en serio. No podría recomendarlo lo suficiente. Definitivamente trabajaremos con Ruben en el futuro para cualquier colocación o necesidades de administrador de propiedades.',
      'testimonials.3': '¡Ruben es increíble! Si hubiera una manera de darle 6 estrellas lo haría. Es súper receptivo y realmente se mantiene al tanto de las cosas. Fue muy reconfortante saber que teníamos a alguien en quien realmente podíamos confiar durante todo el proceso. Hizo que todo fuera muy suave y sin problemas, respondió todas nuestras preguntas y tuvo excelentes ideas. Si estás buscando un agente inmobiliario, Ruben superará tus expectativas.',
      'testimonials.4': 'Ruben es excepcional en su oficio y hace un trabajo increíble guiando a sus clientes en cada paso del camino en una transacción inmobiliaria. Tiene un profundo conocimiento del mercado, gran atención al detalle y siempre pone los intereses de sus clientes primero. Puedes esperar grandes resultados cuando trabajes con Ruben.',
      'testimonials.5': 'He tenido el placer de trabajar junto a Ruben en múltiples transacciones. Su pasión por servir y educar a sus clientes en el camino es verdaderamente notable. Ruben es trabajador, diligente con los detalles y ¡hace el trabajo! ¡Lo recomiendo altamente no solo para bienes raíces sino también para administración de propiedades!',
      'testimonials.6': 'Ruben es muy conocedor en el proceso de compra y venta de casas. Educa a sus clientes. Explica todo claramente. Siempre contesta su teléfono. Hace que el proceso de compra/venta de casa sea suave. Es paciente y tiene mucha perspicacia y experiencia en la industria inmobiliaria. Ruben escucha las necesidades de sus clientes.',
      'testimonials.7': 'Trabajar con Ruben ha sido un placer absoluto de principio a fin. No solo es un agente inmobiliario increíblemente hábil, sino que va más allá ofreciendo una mentoría invaluable en el camino. Como compradora de casa por primera vez, estaba nerviosa por todo el proceso, pero la guía y experiencia de Ruben me tranquilizaron de inmediato. Lo que distingue a Ruben es su compromiso genuino con el éxito de sus clientes. Se tomó el tiempo para entender mis necesidades y respondió pacientemente todas mis preguntas, asegurándose de que me sintiera confiada en cada paso.',
      'testimonials.8': 'Si estás buscando la mejor experiencia de compra de casa, tienes que trabajar con Ruben. Ruben tiene todas las cualidades para no solo hacer realidad tus sueños de propiedad de casa sino también hacer que el viaje sea una experiencia agradable. Asume cada obstáculo que pueda surgir con profesionalismo y una gran actitud. Estoy orgullosa de decir que es mi socio agente inmobiliario.',
      'testimonials.9': 'Ruben y su equipo fueron más allá de las expectativas para nosotros. Representó muy bien nuestros intereses como agente comprador. No solo desde el punto de vista del trabajo típico de corredor, sino también su lista de contactos de servicios profesionales. Tiene una red estelar de personas que nos impresionaron durante todo el proceso. ¡Gracias Ruben!',
      'testimonials.10': 'Nos refirieron a Ruben por un amigo que elogió su conocimiento. Disfrutamos su entusiasmo y su experiencia en su campo. Nos iluminó sobre algunas cosas en las que no habríamos pensado, fue muy informativo y ansioso por responder cualquier y todas las preguntas, y fue fácil trabajar con él. Queremos agradecerle por su tiempo, energía y esfuerzo en asistirnos y siempre estar disponible para nuestras 100 preguntas. ¡Ruben es definitivamente nuestro tipo de persona para el futuro!',
      'service_areas.title': 'Experiencia Local Donde Más Importa',
      'service_areas.subtitle': 'Conocimiento de escuelas, desplazamientos y mercados vecinales.',
      'service_areas.map_instruction': 'Haz clic en las ubicaciones para explorar cada área',
      'service_areas.button': 'Explora Mis Áreas de Servicio',
      'features.button': 'Ver Mis Certificaciones',
      'service_areas.san_marcos.description': 'San Marcos es el centro de North County. Conocido por sus excelentes escuelas, vecindarios familiares y escena empresarial en expansión, es una ubicación principal tanto para compradores primerizos como para inversionistas experimentados.',
      'service_areas.escondido.description': 'Escondido es una comunidad vibrante en North County San Diego, que ofrece excelentes oportunidades tanto para residentes como para inversionistas. Con su ubicación estratégica y crecientes comodidades, representa una de las áreas más prometedoras de la región.',
      'service_areas.vista.description': 'Vista combina asequibilidad con oportunidad, haciéndola atractiva tanto para house hackers como para familias. Con su mezcla de comodidad suburbana y nuevo desarrollo, Vista continúa atrayendo a aquellos que buscan crecimiento a largo plazo.',
      'service_areas.carlsbad.description': 'Carlsbad es la vida costera en su mejor expresión. Las familias aman sus playas y escuelas de alto rango, mientras que los inversionistas ven una fuerte demanda de alquiler y potencial de apreciación. Es el equilibrio perfecto entre estilo de vida y retorno.',
      'service_areas.oceanside.description': 'Oceanside combina un ambiente de playa relajado con un centro revitalizado y presencia militar. Desde oportunidades de préstamos VA hasta inversiones en el frente marítimo, ofrece algo único para veteranos, familias e inversionistas.',
      'footer.title': '¿Listo para Comenzar tu Viaje Inmobiliario?',
      'footer.subtitle': 'Hablemos de tus objetivos y creemos una estrategia que funcione para ti.',
      'footer.services_title': 'Servicios',
      'footer.service1': 'Veteranos',
      'footer.service2': 'Inversionistas',
      'footer.service3': 'Compradores Primerizos',
      'footer.service4': 'Administración de Propiedades',
      'footer.areas_title': 'Áreas',
      'footer.contact_title': 'Contacto',
      'footer.slogan': 'Tu Hogar en North County Comienza Aquí',
      'footer.copyright': '© 2025 Ruben Real Estate. Todos los derechos reservados. | Realty of America (ROA)',
      // Legal & compliance
      'legal.and': 'y',
      'contact.form.opt_in': "Acepto ser contactado por Ruben Real Estate vía llamada, correo electrónico y mensaje de texto para servicios inmobiliarios. Para darte de baja, puedes responder 'stop' en cualquier momento o 'help' para asistencia. También puedes hacer clic en el enlace para cancelar suscripción en los correos. Pueden aplicarse cargos por mensajes y datos. La frecuencia de mensajes puede variar.",
      'legal.no_sale_share': 'Los datos no se venderán ni compartirán con terceros con fines promocionales o de marketing.',
      'legal.link.privacy': 'Política de Privacidad',
      'legal.link.terms': 'Términos de Uso',
      'legal.privacy.title': 'Política de Privacidad',
      'legal.privacy.intro': 'Gracias por elegir Ruben Real Estate. Esta Política de Privacidad explica cómo recopilamos, usamos y protegemos su información cuando utiliza nuestro sitio web y servicios.',
      'legal.privacy.consent.title': 'Consentimiento',
      'legal.privacy.consent': 'Al usar nuestro sitio web, usted acepta esta Política de Privacidad y sus términos.',
      'legal.privacy.information.title': 'Información que Recopilamos',
      'legal.privacy.collect': 'Podemos recopilar información personal como su nombre, correo electrónico, número de teléfono y cualquier otro dato que decida proporcionar cuando nos contacta o envía formularios en nuestro sitio.',
      'legal.privacy.use.title': 'Cómo Usamos su Información',
      'legal.privacy.use.1': 'Proveer, operar y mantener nuestro sitio web y servicios',
      'legal.privacy.use.2': 'Comunicarnos con usted sobre servicios inmobiliarios, incluyendo por llamada, correo y mensaje de texto',
      'legal.privacy.use.3': 'Responder a sus consultas y brindar soporte al cliente',
      'legal.privacy.use.4': 'Mejorar y personalizar su experiencia',
      'legal.privacy.use.5': 'Detectar, prevenir y abordar fraudes o problemas de seguridad',
      'legal.privacy.logfiles.title': 'Archivos de Registro',
      'legal.privacy.logfiles': 'Como muchos sitios web, usamos archivos de registro para análisis y administración del sitio. Esto puede incluir direcciones IP, tipo de navegador, ISP, fecha/hora, páginas de referencia/salida y conteo de clics. Esta información no está vinculada a datos personales identificables.',
      'legal.privacy.cookies.title': 'Cookies',
      'legal.privacy.cookies': 'Usamos cookies para recordar preferencias y mejorar su experiencia. Puede controlar las cookies en la configuración de su navegador.',
      'legal.privacy.rights.title': 'Sus Derechos',
      'legal.privacy.rights': 'Según su ubicación, puede tener derechos para acceder, corregir, eliminar o restringir el procesamiento de sus datos personales, y oponerse al procesamiento o solicitar portabilidad de datos. Para ejercer estos derechos, contáctenos.',
      'legal.privacy.children.title': 'Información de los Niños',
      'legal.privacy.children': 'No recopilamos deliberadamente información personal de menores de 13 años. Si cree que un menor nos ha proporcionado datos personales, contáctenos para eliminarlos.',
      'legal.privacy.changes.title': 'Cambios a Esta Política',
      'legal.privacy.changes': 'Podemos actualizar esta Política de Privacidad periódicamente. Los cambios se publicarán en esta página y serán efectivos cuando se publiquen.',
      'legal.privacy.contact.title': 'Contacto',
      'legal.privacy.contact_label': 'Para preguntas sobre esta Política de Privacidad o para ejercer sus derechos, contáctenos en',
      'legal.terms.title': 'Términos y Condiciones de Uso del Sitio Web',
      'legal.terms.terms': 'Al acceder a este sitio web, usted acepta quedar sujeto a estos Términos y Condiciones de Uso del Sitio Web y acepta que es responsable del cumplimiento de las leyes locales aplicables. Si no está de acuerdo con alguno de estos términos, tiene prohibido acceder a este sitio. Los materiales de este sitio web están protegidos por leyes de derechos de autor y marcas registradas.',
      'legal.terms.use_license.title': 'Licencia de Uso',
      'legal.terms.use_license.body': "Se otorga permiso para descargar temporalmente una copia de los materiales del sitio web de Ruben Real Estate para visualización transitoria personal y no comercial. Esta es una concesión de licencia, no una transferencia de título, y bajo esta licencia usted no puede: modificar o copiar los materiales; usar los materiales para cualquier propósito comercial o para exhibición pública; intentar realizar ingeniería inversa de cualquier software del sitio; eliminar avisos de derechos de autor u otras anotaciones de propiedad; o transferir los materiales a otra persona o 'reflejar' los materiales en cualquier otro servidor. Ruben Real Estate puede dar por terminada esta licencia ante violaciones de cualquiera de estas restricciones. Al finalizar, su derecho de visualización también finalizará y deberá destruir cualquier material descargado en su posesión ya sea en formato impreso o electrónico.",
      'legal.terms.disclaimer.title': 'Descargo de Responsabilidad',
      'legal.terms.disclaimer.body': 'Todos los materiales de este sitio web se proporcionan “tal cual”. Ruben Real Estate no ofrece garantías, expresas o implícitas, y por la presente rechaza y niega todas las demás garantías. Además, Ruben Real Estate no hace representaciones sobre la exactitud o confiabilidad del uso de los materiales en su sitio web o en relación con dichos materiales o cualquier sitio vinculado a este sitio.',
      'legal.terms.limitations.title': 'Limitaciones',
      'legal.terms.limitations.body': 'En ningún caso Ruben Real Estate o sus proveedores serán responsables por daños que surjan del uso o la imposibilidad de uso de los materiales del sitio web, incluso si Ruben Real Estate o un representante autorizado ha sido notificado de la posibilidad de dichos daños. Algunas jurisdicciones no permiten limitaciones en garantías implícitas o limitaciones de responsabilidad por daños incidentales; estas limitaciones pueden no aplicarse a usted.',
      'legal.terms.revisions.title': 'Revisiones y Erratas',
      'legal.terms.revisions.body': 'Los materiales del sitio web pueden incluir errores técnicos, tipográficos o fotográficos. Ruben Real Estate no garantiza que cualquiera de los materiales en su sitio web sea preciso, completo o actual. Ruben Real Estate puede realizar cambios a los materiales en su sitio web en cualquier momento sin previo aviso. Ruben Real Estate no se compromete a actualizar los materiales.',
      'legal.terms.links.title': 'Enlaces',
      'legal.terms.links.body': 'Ruben Real Estate no ha revisado todos los sitios enlazados a su sitio web y no es responsable del contenido de dichos sitios. La inclusión de cualquier enlace no implica respaldo por parte de Ruben Real Estate. El uso de cualquier sitio web enlazado es bajo su propio riesgo.',
      'legal.terms.modifications.title': 'Modificaciones de los Términos',
      'legal.terms.modifications.body': 'Ruben Real Estate puede revisar estos Términos de Uso en cualquier momento sin previo aviso. Al usar este sitio web, usted acepta quedar sujeto a la versión vigente de estos Términos y Condiciones de Uso.',
      'legal.terms.privacy_prompt': 'Su Privacidad: Por favor lea nuestra',
      'legal.terms.governing_law.title': 'Ley Aplicable',
      'legal.terms.governing_law.body': 'Cualquier reclamación relacionada con este sitio web se regirá por las leyes de los Estados Unidos sin tener en cuenta sus disposiciones sobre conflictos de leyes.',
      'legal.terms.contact.title': 'Contáctenos',
      'legal.terms.contact.body': 'Para preguntas sobre estos Términos, contáctenos en ruben.o.banuelos@gmail.com o (541) 602-1026.',
    }
  }

  const t = (key: string): string => {
    // During SSR or before client hydration, always return English
    if (!isClient) {
      return translations['en'][key as keyof typeof translations['en']] || key
    }
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return { language, toggleLanguage, t }
}